// ---- BEGIN position_map.cpp ----
#include "config.h"

// Generated by the selftest mapping sweep, then every note raised 12: the
// sweep assumed A2 for the lowest key, a tuner on the injected notes said A3
// (57). Range is now the toy's own, A3-C6, so MIDI and CV play in unison
// with it. The button board's seven (cc28-34) were added by hand from the
// injection walk, and scan since that board moved to the expander side.
// Index = col * 6 + row.

const PosMap POSITION_MAP[N_POS] = {
    {K_NONE, 0},
    {K_NOTE, 81},
    {K_CC, 24}, // banjo
    {K_NOTE, 73},
    {K_NOTE, 57},
    {K_NOTE, 65}, // col 0
    {K_NONE, 0},
    {K_NOTE, 82},
    {K_CC, 25}, // music
    {K_NOTE, 74},
    {K_NOTE, 58},
    {K_NOTE, 66}, // col 1
    {K_NONE, 0},
    {K_NOTE, 83},
    {K_CC, 27}, // catface
    {K_NOTE, 75},
    {K_NOTE, 59},
    {K_NOTE, 67}, // col 2
    {K_CC, 29}, // play
    {K_CC, 21}, // bells
    {K_CC, 32}, // samba
    {K_NOTE, 78},
    {K_NOTE, 62},
    {K_NOTE, 70}, // col 3
    {K_CC, 28}, // record
    {K_CC, 20}, // piano
    {K_CC, 31}, // blues
    {K_NOTE, 77},
    {K_NOTE, 61},
    {K_NOTE, 69}, // col 4
    {K_NONE, 0},
    {K_NOTE, 84},
    {K_CC, 30}, // rock
    {K_NOTE, 76},
    {K_NOTE, 60},
    {K_NOTE, 68}, // col 5
    {K_NONE, 0},
    {K_CC, 22}, // meow
    {K_CC, 33}, // techno
    {K_NOTE, 79},
    {K_NOTE, 63},
    {K_NOTE, 71}, // col 6
    {K_CC, 26}, // stop
    {K_CC, 23}, // organ
    {K_CC, 34}, // disco
    {K_NOTE, 80},
    {K_NOTE, 64},
    {K_NOTE, 72}, // col 7
};
// ---- END position_map.cpp ----